# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fe9b5e8c90817162afe29cf8c4ff8de1b38cb2e9d622e3a4e52cf5f3a4ab1abb5959f6e4a9f54bdb6e608c391c5291dd4960d765cd322a114f1feeffd6ac265
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"]%>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST"]%>

test:
  secret_key_base: aa686f93beb6ef7ad10a0b634bba0fb221a1ffc9f13679a3768fae2459da454b1cbcabe118306eef9a070705c2ea42d2d25011fbe37f8fe268abee00b752f3c2
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"]%>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST"]%>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"]%>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"]%>

